# Generated by Django 5.2.1 on 2025-11-22 22:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_inventario', '0001_initial'),
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100, unique=True, verbose_name='País/Nación')),
                ('gentilicio', models.CharField(help_text='Ingrese el gentilicio', max_length=100, verbose_name='Gentilicio')),
                ('iso_nac', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
                'permissions': [('sys_view_nacionalidad', 'System: Puede ver Nacionalidades'), ('sys_add_nacionalidad', 'System: Puede agregar Nacionalidades'), ('sys_change_nacionalidad', 'System: Puede cambiar Nacionalidades'), ('sys_delete_nacionalidad', 'System: Puede eliminar Nacionalidades')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la profesión u oficio', max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Profesión',
                'verbose_name_plural': 'Profesiones',
                'ordering': ['nombre'],
                'permissions': [('sys_view_profesion', 'System: Puede ver Profesiones'), ('sys_add_profesion', 'System: Puede agregar Profesiones'), ('sys_change_profesion', 'System: Puede cambiar Profesiones'), ('sys_delete_profesion', 'System: Puede eliminar Profesiones')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='TipoCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'permissions': [('sys_view_tipocargo', 'System: Puede ver Tipos de Cargo'), ('sys_add_tipocargo', 'System: Puede agregar Tipos de Cargo'), ('sys_change_tipocargo', 'System: Puede cambiar Tipos de Cargo'), ('sys_delete_tipocargo', 'System: Puede eliminar Tipos de Cargo')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='TipoReconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Reconocimiento')),
            ],
            options={
                'verbose_name': 'Tipo de Reconocimiento',
                'verbose_name_plural': 'Tipos de Reconocimientos',
                'ordering': ['nombre'],
                'permissions': [('sys_view_tiporeconocimiento', 'System: Puede ver Tipos de Reconocimientos'), ('sys_add_tiporeconocimiento', 'System: Puede agregar Tipos de Reconocimientos'), ('sys_change_tiporeconocimiento', 'System: Puede cambiar Tipos de Reconocimientos'), ('sys_delete_tiporeconocimiento', 'System: Puede eliminar Tipos de Reconocimientos')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Cargo/Rango')),
                ('tipo_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='gestion_voluntarios.tipocargo')),
            ],
            options={
                'verbose_name': 'Cargo / Rango',
                'verbose_name_plural': 'Cargos / Rangos',
                'ordering': ['tipo_cargo', 'nombre'],
                'permissions': [('sys_view_cargo', 'System: Puede ver Cargos / Rangos'), ('sys_add_cargo', 'System: Puede agregar Cargos / Rangos'), ('sys_change_cargo', 'System: Puede cambiar Cargos / Rangos'), ('sys_delete_cargo', 'System: Puede eliminar Cargos / Rangos')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_voluntario', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar de Nacimiento')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('P', 'Prefiero no decirlo')], max_length=1, null=True, verbose_name='Género')),
                ('estado_civil', models.CharField(blank=True, choices=[('SOL', 'Soltero(a)'), ('CAS', 'Casado(a)'), ('CON', 'Conviviente'), ('DIV', 'Divorciado(a)'), ('VIU', 'Viudo(a)')], max_length=3, null=True, verbose_name='Estado Civil')),
                ('domicilio_calle', models.CharField(blank=True, max_length=255, null=True)),
                ('domicilio_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_primer_ingreso', models.DateField(blank=True, help_text='Fecha de ingreso a su primera estación (para calcular antigüedad total)', null=True, verbose_name='Fecha de Primer Ingreso al Servicio')),
                ('numero_registro_bomberil', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='N° Registro General de Bomberos')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='voluntarios/imagen/main/')),
                ('imagen_thumb_medium', models.ImageField(blank=True, editable=False, null=True, upload_to='voluntarios/imagen/medium/', verbose_name='Thumbnail (600x600)')),
                ('imagen_thumb_small', models.ImageField(blank=True, editable=False, null=True, upload_to='voluntarios/imagen/small/', verbose_name='Thumbnail (50x50)')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('domicilio_comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_inventario.comuna')),
                ('nacionalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_voluntarios.nacionalidad', verbose_name='Nacionalidad')),
                ('profesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_voluntarios.profesion', verbose_name='Profesión Civil')),
            ],
            options={
                'verbose_name': 'Voluntario',
                'verbose_name_plural': 'Voluntarios',
                'permissions': [('sys_view_voluntario', 'System: Puede ver Voluntarios'), ('sys_add_voluntario', 'System: Puede agregar Voluntarios'), ('sys_change_voluntario', 'System: Puede cambiar Voluntarios'), ('sys_delete_voluntario', 'System: Puede eliminar Voluntarios')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='HistorialSancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sancion', models.CharField(choices=[('amonestacion_verbal', 'Amonestación Verbal'), ('amonestacion_escrita', 'Amonestación Escrita'), ('suspension', 'Suspensión'), ('expulsion', 'Expulsión')], max_length=30)),
                ('descripcion', models.TextField(verbose_name='Descripción y Motivo')),
                ('documento_adjunto', models.FileField(blank=True, null=True, upload_to='sanciones/')),
                ('fecha_evento', models.DateField(verbose_name='Fecha de la Sanción')),
                ('fecha_inicio_suspension', models.DateField(blank=True, null=True)),
                ('fecha_fin_suspension', models.DateField(blank=True, null=True)),
                ('es_historico', models.BooleanField(default=False)),
                ('estacion_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanciones_emitidas', to='gestion_inventario.estacion')),
                ('estacion_registra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanciones_registradas', to='gestion_inventario.estacion')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_sanciones', to='gestion_voluntarios.voluntario')),
            ],
            options={
                'verbose_name': 'Historial de Sanción',
                'verbose_name_plural': 'Historial de Sanciones',
                'ordering': ['-fecha_evento'],
                'permissions': [('sys_view_historialsancion', 'System: Puede ver Historial de Sanciones'), ('sys_add_historialsancion', 'System: Puede agregar Historial de Sanciones'), ('sys_change_historialsancion', 'System: Puede cambiar Historial de Sanciones'), ('sys_delete_historialsancion', 'System: Puede eliminar Historial de Sanciones')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='HistorialReconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_personalizada', models.CharField(blank=True, help_text="Use este campo si no es un premio estándar (ej: 'Medalla al Valor')", max_length=255, null=True)),
                ('fecha_evento', models.DateField(verbose_name='Fecha del Reconocimiento')),
                ('ambito', models.CharField(help_text="Quién otorga el premio (Ej: 'Compañía', 'Cuerpo de Bomberos Florida', 'Junta Nacional')", max_length=255)),
                ('es_historico', models.BooleanField(default=False)),
                ('estacion_registra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconocimientos_registrados', to='gestion_inventario.estacion')),
                ('tipo_reconocimiento', models.ForeignKey(blank=True, help_text='Seleccione si es un premio estándar (ej: por años de servicio)', null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_voluntarios.tiporeconocimiento')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_reconocimientos', to='gestion_voluntarios.voluntario')),
            ],
            options={
                'verbose_name': 'Historial de Reconocimiento',
                'verbose_name_plural': 'Historial de Reconocimientos',
                'ordering': ['-fecha_evento'],
                'permissions': [('sys_view_historialreconocimiento', 'System: Puede ver Historial de Reconocimientos'), ('sys_add_historialreconocimiento', 'System: Puede agregar Historial de Reconocimientos'), ('sys_change_historialreconocimiento', 'System: Puede cambiar Historial de Reconocimientos'), ('sys_delete_historialreconocimiento', 'System: Puede eliminar Historial de Reconocimientos')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='HistorialPertenencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_historico', models.BooleanField(default=False, help_text='Marcar si es un registro antiguo (backfill)')),
                ('tipo_evento', models.CharField(choices=[('ingreso', 'Ingreso'), ('renuncia', 'Renuncia'), ('reincorporacion', 'Reincorporación'), ('traslado', 'Traslado')], max_length=20)),
                ('fecha_evento', models.DateField(verbose_name='Fecha del Evento')),
                ('descripcion_adicional', models.TextField(blank=True, null=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voluntarios_historicos', to='gestion_inventario.estacion')),
                ('estacion_registra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_pertenencia', to='gestion_inventario.estacion')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_pertenencia', to='gestion_voluntarios.voluntario')),
            ],
            options={
                'verbose_name': 'Evento de Pertenencia',
                'verbose_name_plural': 'Historial de Pertenencia',
                'ordering': ['-fecha_evento'],
                'permissions': [('sys_view_historialpertenencia', 'System: Puede ver Historial de Pertenencia'), ('sys_add_historialpertenencia', 'System: Puede agregar Historial de Pertenencia'), ('sys_change_historialpertenencia', 'System: Puede cambiar Historial de Pertenencia'), ('sys_delete_historialpertenencia', 'System: Puede eliminar Historial de Pertenencia')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='HistorialCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=255)),
                ('institucion', models.CharField(help_text="Ej: 'ANB', 'Estación', 'Externo'", max_length=255)),
                ('fecha_curso', models.DateField(verbose_name='Fecha de Aprobación')),
                ('es_historico', models.BooleanField(default=False)),
                ('estacion_registra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos_registrados', to='gestion_inventario.estacion')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cursos', to='gestion_voluntarios.voluntario')),
            ],
            options={
                'verbose_name': 'Historial de Curso',
                'verbose_name_plural': 'Historial de Cursos',
                'ordering': ['-fecha_curso'],
                'permissions': [('sys_view_historialcurso', 'System: Puede ver Historial de Cursos'), ('sys_add_historialcurso', 'System: Puede agregar Historial de Cursos'), ('sys_change_historialcurso', 'System: Puede cambiar Historial de Cursos'), ('sys_delete_historialcurso', 'System: Puede eliminar Historial de Cursos')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='HistorialCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(help_text="Dónde ejerció el cargo (Ej: 'Compañía', 'Cuerpo de Bomberos Florida', 'Consejo Regional', 'Junta Nacional')", max_length=255)),
                ('es_historico', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Término')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voluntarios_con_cargo', to='gestion_voluntarios.cargo')),
                ('estacion_registra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos_registrados', to='gestion_inventario.estacion')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cargos', to='gestion_voluntarios.voluntario')),
            ],
            options={
                'verbose_name': 'Historial de Cargo',
                'verbose_name_plural': 'Historial de Cargos',
                'ordering': ['-fecha_inicio'],
                'permissions': [('sys_view_historialcargo', 'System: Puede ver Historial de Cargos'), ('sys_add_historialcargo', 'System: Puede agregar Historial de Cargos'), ('sys_change_historialcargo', 'System: Puede cambiar Historial de Cargos'), ('sys_delete_historialcargo', 'System: Puede eliminar Historial de Cargos')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='AnotacionHojaVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción de la anotación')),
                ('fecha_evento', models.DateField(verbose_name='Fecha')),
                ('es_historico', models.BooleanField(default=False)),
                ('estacion_registra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anotaciones_registradas', to='gestion_inventario.estacion')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_anotaciones', to='gestion_voluntarios.voluntario')),
            ],
            options={
                'verbose_name': 'Anotación en Hoja de Vida',
                'verbose_name_plural': 'Anotaciones en Hoja de Vida',
                'ordering': ['-fecha_evento'],
                'permissions': [('sys_view_anotacionhojavida', 'System: Puede ver Anotaciones en Hoja de Vida'), ('sys_add_anotacionhojavida', 'System: Puede agregar Anotaciones en Hoja de Vida'), ('sys_change_anotacionhojavida', 'System: Puede cambiar Anotaciones en Hoja de Vida'), ('sys_delete_anotacionhojavida', 'System: Puede eliminar Anotaciones en Hoja de Vida')],
                'default_permissions': [],
            },
        ),
    ]
