# Generated by Django 5.2.1 on 2025-11-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Teléfono de contacto del voluntario'),
        ),
    ]
