# Generated by Django 5.2.1 on 2025-11-22 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('gestion_inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='correo electrónico')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('phone', models.CharField(blank=True, max_length=9, null=True, verbose_name='Teléfono')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='usuarios/avatar/main/')),
                ('avatar_thumb_small', models.ImageField(blank=True, null=True, upload_to='usuarios/avatar/small/')),
                ('avatar_thumb_medium', models.ImageField(blank=True, null=True, upload_to='usuarios/avatar/medium/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'permissions': [('sys_view_usuario', 'System: Puede ver usuarios'), ('sys_add_usuario', 'System: Puede agregar usuarios'), ('sys_change_usuario', 'System: Puede cambiar usuarios'), ('sys_delete_usuario', 'System: Puede eliminar usuarios')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('verbo', models.CharField(max_length=255)),
                ('objetivo_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('objetivo_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to=settings.AUTH_USER_MODEL)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_inventario.estacion')),
                ('objetivo_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-fecha'],
                'permissions': [('sys_view_registro_actividad', 'System: Puede ver registros de actividad'), ('sys_add_registro_actividad', 'System: Puede agregar registros de actividad'), ('sys_change_registro_actividad', 'System: Puede cambiar registros de actividad'), ('sys_delete_registro_actividad', 'System: Puede eliminar registros de actividad')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='(Descripción)')),
                ('estacion', models.ForeignKey(blank=True, help_text='Dejar en blanco para crear un rol universal.', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_inventario.estacion')),
                ('permisos', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='permisos')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'ordering': ['nombre'],
                'permissions': [('sys_view_rol', 'System: Puede ver los roles '), ('sys_add_rol', 'System: Puede agregar roles'), ('sys_change_rol', 'System: Puede cambiar usuarios'), ('sys_delete_rol', 'System: Puede eliminar usuarios')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='gestion_inventario.estacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(related_name='asignaciones', to='gestion_usuarios.rol')),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'permissions': [('sys_view_membresia', 'System: Puede ver membresías'), ('sys_add_membresia', 'System: Puede agregar membresías'), ('sys_change_membresia', 'System: Puede cambiar membresías'), ('sys_delete_membresia', 'System: Puede eliminar membresías'), ('acceso_gestion_usuarios', 'Puede acceder al módulo de Gestión de Usuarios'), ('accion_gestion_usuarios_crear_usuario', 'Puede crear y registrar nuevos usuarios'), ('accion_gestion_usuarios_modificar_info', 'Puede modificar la información personal de un usuario'), ('accion_gestion_usuarios_restablecer_pass', 'Puede restablecer la contraseña de un usuario'), ('accion_gestion_usuarios_ver_roles', 'Puede ver los roles y sus permisos'), ('accion_gestion_usuarios_gestionar_roles', 'Puede crear, editar, eliminar y asignar permisos a los roles'), ('accion_gestion_usuarios_ver_compania', 'Puede ver a los usuarios de la compañía'), ('accion_gestion_usuarios_ver_permisos', 'Puede ver los permisos de los usuarios'), ('accion_gestion_usuarios_asignar_roles', 'Puede asignar y cambiar roles a un usuario'), ('accion_gestion_usuarios_desactivar_cuenta', 'Puede desactivar o reactivar la cuenta de un usuario'), ('accion_gestion_usuarios_finalizar_membresia', 'Puede finalizar la membresía de un usuario'), ('accion_gestion_usuarios_ver_auditoria', 'Puede ver el registro de actividad (auditoría) y el historial de membresías'), ('accion_gestion_usuarios_forzar_logout', 'Puede forzar el cierre de sesión de los usuarios'), ('accion_gestion_usuarios_generar_reportes', 'Puede generar reportes'), ('acceso_gestion_inventario', 'Puede acceder al módulo de Gestión de Inventario'), ('accion_gestion_inventario_ver_ubicaciones', 'Puede ver la lista de Áreas, Vehículos y Compartimentos'), ('accion_gestion_inventario_gestionar_ubicaciones', 'Puede crear, editar y eliminar Áreas, Vehículos y Compartimentos'), ('accion_gestion_inventario_ver_proveedores', 'Puede ver la lista de Proveedores y sus contactos'), ('accion_gestion_inventario_gestionar_proveedores', 'Puede crear, editar y eliminar Proveedores y sus contactos'), ('accion_gestion_inventario_ver_catalogos', 'Puede ver el Catálogo Local de la estación y el Catálogo Global'), ('accion_gestion_inventario_gestionar_catalogo_local', 'Puede añadir y administrar el Catálogo Local de productos'), ('accion_gestion_inventario_crear_producto_global', 'Puede crear nuevos productos en el Catálogo Global'), ('accion_gestion_inventario_ver_stock', 'Puede consultar el stock y ver el detalle de las existencias'), ('accion_gestion_inventario_recepcionar_stock', 'Puede recepcionar y registrar nuevas existencias (stock)'), ('accion_gestion_inventario_gestionar_stock_interno', 'Puede consumir, ajustar y transferir existencias internamente'), ('accion_gestion_inventario_gestionar_bajas_stock', 'Puede dar de baja, anular o reportar extravío de existencias'), ('accion_gestion_inventario_ver_prestamos', 'Puede ver el historial de préstamos y sus detalles'), ('accion_gestion_inventario_gestionar_prestamos', 'Puede crear préstamos, gestionar devoluciones y administrar destinatarios'), ('accion_gestion_inventario_trasladar_stock_externo', 'Puede trasladar existencias (stock) a otra estación'), ('accion_gestion_inventario_ver_historial_movimientos', 'Puede ver el historial de movimientos del inventario'), ('accion_gestion_inventario_imprimir_etiquetas_qr', 'Puede generar e imprimir etiquetas QR'), ('accion_gestion_inventario_realizar_conteo_fisico', 'Puede iniciar y gestionar un Conteo Físico (Inventario)'), ('accion_gestion_inventario_generar_reportes', 'Puede generar reportes'), ('acceso_gestion_mantenimiento', 'Puede acceder al módulo de Mantenimiento'), ('accion_gestion_mantenimiento_ver_ordenes', 'Puede ver los planes de mantenimiento y las órdenes de trabajo'), ('accion_gestion_mantenimiento_gestionar_planes', 'Puede gestionar los planes de mantenimiento'), ('accion_gestion_mantenimiento_gestionar_ordenes', 'Puede gestionar las órdenes de trabajo y registrar tareas'), ('accion_gestion_mantenimiento_generar_reportes', 'Puede generar reportes'), ('acceso_gestion_voluntarios', 'Puede acceder al módulo de Voluntarios'), ('accion_gestion_voluntarios_ver_voluntarios', 'Puede ver a los voluntarios de la compañía'), ('accion_gestion_voluntarios_gestionar_voluntarios', 'Puede gestionar a los voluntarios de la compañía'), ('accion_gestion_voluntarios_generar_hoja_vida', 'Puede generar la hoja de vida de un voluntario en PDF'), ('accion_gestion_voluntarios_gestionar_datos_normalizacion', 'Puede gestionar los cargos y profesiones de la compañía'), ('accion_gestion_voluntarios_generar_reportes', 'Puede generar reportes'), ('acceso_gestion_medica', 'Puede acceder al módulo de Fichas médicas'), ('accion_gestion_medica_ver_fichas_medicas', 'Puede ver las fichas médicas de los voluntarios de la compañía'), ('accion_gestion_medica_gestionar_fichas_medicas', 'Puede gestionar las fichas médicas de los voluntarios de la compañía'), ('accion_gestion_medica_gestionar_datos_normalizacion', 'Puede gestionar enfermedades, medicamentos, cirugías, etc.'), ('accion_gestion_medica_generar_reportes', 'Puede generar reportes'), ('acceso_gestion_documental', 'Puede acceder al módulo de Fichas médicas'), ('accion_gestion_documental_ver_documentos', 'Puede ver los documentos de la compañía'), ('accion_gestion_documental_gestionar_documentos', 'Puede gestionar los documentos de la compañía'), ('accion_gestion_documental_generar_reportes', 'Puede generar reportes')],
                'default_permissions': [],
            },
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.UniqueConstraint(fields=('nombre', 'estacion'), name='rol_unico_por_estacion'),
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.UniqueConstraint(condition=models.Q(('estacion__isnull', True)), fields=('nombre',), name='rol_global_unico'),
        ),
        migrations.AddConstraint(
            model_name='membresia',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVO')), fields=('usuario',), name='membresia_activa_unica_por_usuario'),
        ),
    ]
