# Generated by Django 5.2.1 on 2025-11-23 15:07

import os
from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.conf import settings

def generar_superusuarios(apps, schema_editor):
    # 1. Obtenemos los modelos históricos (versión congelada en el tiempo)
    Usuario = apps.get_model(settings.AUTH_USER_MODEL)
    Voluntario = apps.get_model('gestion_voluntarios', 'Voluntario')
    FichaMedica = apps.get_model('gestion_medica', 'FichaMedica')
    
    # 2. Extraemos datos del .env
    superusers_data = [
        (os.getenv('BOMBERIL_SU1_RUT'), os.getenv('BOMBERIL_SU1_FIRST_NAME'), os.getenv('BOMBERIL_SU1_LAST_NAME'), os.getenv('BOMBERIL_SU1_EMAIL'), os.getenv('BOMBERIL_SU1_PASSWORD')),
        (os.getenv('BOMBERIL_SU2_RUT'), os.getenv('BOMBERIL_SU2_FIRST_NAME'), os.getenv('BOMBERIL_SU2_LAST_NAME'), os.getenv('BOMBERIL_SU2_EMAIL'), os.getenv('BOMBERIL_SU2_PASSWORD')),
        (os.getenv('BOMBERIL_SU3_RUT'), os.getenv('BOMBERIL_SU3_FIRST_NAME'), os.getenv('BOMBERIL_SU3_LAST_NAME'), os.getenv('BOMBERIL_SU3_EMAIL'), os.getenv('BOMBERIL_SU3_PASSWORD')),
    ]

    for rut, first_name, last_name, email, password in superusers_data:
        # Validación básica: Si faltan datos en el .env, saltamos
        if not rut or not password:
            print(f"Saltando creación de superusuario: Faltan credenciales en .env para {rut or 'Desconocido'}")
            continue

        # Idempotencia: Si el usuario ya existe, no hacemos nada (evita crash)
        if Usuario.objects.filter(rut=rut).exists():
            print(f"ℹ El superusuario {rut} ya existe.")
            # Si el usuario ya existe, intentamos obtener su voluntario para asegurar que tenga ficha
            usuario_existente = Usuario.objects.get(rut=rut)
            
            # Lógica de recuperación por si la migración corrió a medias antes
            voluntario, _ = Voluntario.objects.get_or_create(usuario=usuario_existente)
            if not FichaMedica.objects.filter(voluntario=voluntario).exists():
                FichaMedica.objects.create(voluntario=voluntario)
                print(f"   -> Ficha médica creada para usuario existente {rut}")
            continue

        print(f"Creando superusuario: {rut}")
        
        # 3. Creación del Usuario (Manual, seteando flags de staff)
        nuevo_usuario = Usuario.objects.create(
            rut=rut,
            first_name=first_name,
            last_name=last_name,
            email=email,
            password=make_password(password),
            is_staff=True,
            is_superuser=True,
            is_active=True
        )

        # 4. Creación del Voluntario
        # Usamos get_or_create para obtener la instancia del objeto 'voluntario'
        voluntario, created = Voluntario.objects.get_or_create(
            usuario=nuevo_usuario
        )

        # 5. Creación de la Ficha Médica
        if not FichaMedica.objects.filter(voluntario=voluntario).exists():
            FichaMedica.objects.create(
                voluntario=voluntario,
                # Los demás campos se quedan en null/default según tu modelo
            )

def revertir_superusuarios(apps, schema_editor):
    """
    Permite hacer rollback de la migración borrando los usuarios creados.
    """
    Usuario = apps.get_model(settings.AUTH_USER_MODEL)
    usernames = [
        os.getenv('BOMBERIL_SU1_RUT'),
        os.getenv('BOMBERIL_SU2_RUT'),
        os.getenv('BOMBERIL_SU3_RUT')
    ]
    # Filtramos los Nones por si faltan variables
    usernames = [u for u in usernames if u]
    
    # Borramos (El borrado en cascada de Django se encargará del Voluntario)
    Usuario.objects.filter(rut__in=usernames).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
        ('gestion_voluntarios', '0001_initial'),
        ('gestion_medica', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(generar_superusuarios, revertir_superusuarios),
    ]