# Generated by Django 5.2.1 on 2025-11-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermissionAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Ancla de Permiso de Módulo',
                'verbose_name_plural': 'Anclas de Permisos de Módulo',
                'default_permissions': [],
            },
        ),
    ]
