# Generated by Django 5.2.1 on 2025-11-22 22:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanActivoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ultima_mantencion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Última Mantención')),
                ('horas_uso_en_ultima_mantencion', models.DecimalField(decimal_places=2, default=0.0, help_text='Guarda el total de horas_uso_totales del activo en su última mantención.', max_digits=7, verbose_name='Horas del Activo en Última Mantención')),
            ],
            options={
                'verbose_name': 'Configuración Activo-Plan',
                'verbose_name_plural': 'Configuraciones Activo-Plan',
                'permissions': [('sys_view_planactivoconfig', 'System: Puede ver Configuraciones Activo-Plan'), ('sys_add_planactivoconfig', 'System: Puede agregar Configuraciones Activo-Plan'), ('sys_change_planactivoconfig', 'System: Puede cambiar Configuraciones Activo-Plan'), ('sys_delete_planactivoconfig', 'System: Puede eliminar Configuraciones Activo-Plan')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Plan')),
                ('tipo_trigger', models.CharField(choices=[('TIEMPO', 'Basado en Tiempo'), ('USO', 'Basado en Horas de Uso')], max_length=10, verbose_name='Tipo de Trigger')),
                ('frecuencia', models.CharField(blank=True, choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual'), ('ANUAL', 'Anual')], max_length=10, null=True, verbose_name='Frecuencia (si es por tiempo)')),
                ('intervalo', models.PositiveSmallIntegerField(default=1, help_text="Ej: si frecuencia es 'SEMANAL' e intervalo es 2, será 'cada 2 semanas'", verbose_name='Intervalo')),
                ('horas_uso_trigger', models.DecimalField(blank=True, decimal_places=2, help_text="Ej: 50.00 (para 'cada 50 horas de uso')", max_digits=7, null=True, verbose_name='Horas de Uso (si es por uso)')),
                ('activo_en_sistema', models.BooleanField(default=True, help_text='Desmarque para desactivar este plan sin borrarlo.', verbose_name='Plan Activo')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, help_text='Fecha a partir de la cual comenzará a ejecutarse el plan.', verbose_name='Fecha de Inicio')),
                ('dia_semana', models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Si la frecuencia es SEMANAL, especifique el día exacto.', null=True, verbose_name='Día preferido de la semana')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan de Mantenimiento',
                'verbose_name_plural': 'Planes de Mantenimiento',
                'permissions': [('sys_view_planmantenimiento', 'System: Puede ver Planes de Mantenimiento'), ('sys_add_planmantenimiento', 'System: Puede agregar Planes de Mantenimiento'), ('sys_change_planmantenimiento', 'System: Puede cambiar Planes de Mantenimiento'), ('sys_delete_planmantenimiento', 'System: Puede eliminar Planes de Mantenimiento')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='RegistroMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ejecución')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas de la Ejecución')),
                ('fue_exitoso', models.BooleanField(default=True, help_text='Indica si la mantención fue completada exitosamente.', verbose_name='¿Mantención Exitosa?')),
            ],
            options={
                'verbose_name': 'Registro de Mantenimiento',
                'verbose_name_plural': 'Registros de Mantenimiento',
                'ordering': ['-fecha_ejecucion'],
                'permissions': [('sys_view_registromantenimiento', 'System: Puede ver Registros de Mantenimiento'), ('sys_add_registromantenimiento', 'System: Puede agregar Registros de Mantenimiento'), ('sys_change_registromantenimiento', 'System: Puede cambiar Registros de Mantenimiento'), ('sys_delete_registromantenimiento', 'System: Puede eliminar Registros de Mantenimiento')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='OrdenMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField(verbose_name='Fecha Programada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación Orden')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Cierre Orden')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En Curso'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado de la Orden')),
                ('tipo_orden', models.CharField(choices=[('PROGRAMADA', 'Programada (Trigger)'), ('CORRECTIVA', 'Correctiva (Manual)')], max_length=20, verbose_name='Tipo de Orden')),
                ('activos_afectados', models.ManyToManyField(help_text='Activos que esta orden específica debe revisar.', related_name='ordenes_mantenimiento', to='gestion_inventario.activo', verbose_name='Activos Afectados')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_mantenimiento', to='gestion_inventario.estacion', verbose_name='Estación')),
            ],
            options={
                'verbose_name': 'Orden de Mantenimiento',
                'verbose_name_plural': 'Órdenes de Mantenimiento',
                'ordering': ['-fecha_programada'],
                'permissions': [('sys_view_ordenmantenimiento', 'System: Puede ver Órdenes de Mantenimiento'), ('sys_add_ordenmantenimiento', 'System: Puede agregar Órdenes de Mantenimiento'), ('sys_change_ordenmantenimiento', 'System: Puede cambiar Órdenes de Mantenimiento'), ('sys_delete_ordenmantenimiento', 'System: Puede eliminar Órdenes de Mantenimiento')],
                'default_permissions': [],
            },
        ),
    ]
