# Generated by Django 5.2.1 on 2025-11-22 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_inventario', '0002_initial'),
        ('gestion_mantenimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable Asignado'),
        ),
        migrations.AddField(
            model_name='planactivoconfig',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_plan', to='gestion_inventario.activo', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='activos',
            field=models.ManyToManyField(related_name='planes_asignados', through='gestion_mantenimiento.PlanActivoConfig', to='gestion_inventario.activo', verbose_name='Activos Incluidos'),
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='estacion',
            field=models.ForeignKey(help_text='La estación a la que pertenece este plan de mantenimiento.', on_delete=django.db.models.deletion.CASCADE, related_name='planes_mantenimiento', to='gestion_inventario.estacion', verbose_name='Estación Propietaria'),
        ),
        migrations.AddField(
            model_name='planactivoconfig',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_mantenimiento.planmantenimiento', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='plan_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_generadas', to='gestion_mantenimiento.planmantenimiento', verbose_name='Plan de Origen'),
        ),
        migrations.AddField(
            model_name='registromantenimiento',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_mantenimiento', to='gestion_inventario.activo', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='registromantenimiento',
            name='orden_mantenimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='gestion_mantenimiento.ordenmantenimiento', verbose_name='Orden de Mantenimiento'),
        ),
        migrations.AddField(
            model_name='registromantenimiento',
            name='usuario_ejecutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Ejecutor'),
        ),
        migrations.AlterUniqueTogether(
            name='planactivoconfig',
            unique_together={('plan', 'activo')},
        ),
    ]
