# Generated by Django 5.2.1 on 2025-11-22 22:34

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_activo', models.CharField(blank=True, help_text='ID Interno único generado por el sistema (Ej: ACT-00123)', max_length=50, verbose_name='Código de Activo (ID Interno)')),
                ('numero_serie_fabricante', models.CharField(blank=True, max_length=100)),
                ('horas_uso_totales', models.DecimalField(decimal_places=2, default=0.0, help_text='Total acumulado de horas de uso del activo.', max_digits=7, verbose_name='Horas de Uso Totales')),
                ('notas_adicionales', models.TextField(blank=True, null=True, verbose_name='(opcional) Notas adicionales')),
                ('fecha_fabricacion', models.DateField(blank=True, null=True, verbose_name='Fecha de fabricación')),
                ('fecha_recepcion', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha de Recepción')),
                ('fecha_expiracion', models.DateField(blank=True, help_text='Usar solo para activos que tienen una fecha de caducidad específica.', null=True, verbose_name='Fecha de expiración')),
                ('fin_vida_util_calculada', models.DateField(blank=True, db_index=True, editable=False, null=True, verbose_name='Fin de Vida Útil (Calculada)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='estaciones/imagen/main/', verbose_name='Imagen del activo')),
                ('imagen_thumb_medium', models.ImageField(blank=True, editable=False, null=True, upload_to='estaciones/imagen/medium/', verbose_name='Thumbnail (600x600)')),
                ('imagen_thumb_small', models.ImageField(blank=True, editable=False, null=True, upload_to='estaciones/imagen/small/', verbose_name='Thumbnail (50x50)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'permissions': [('sys_view_activo', 'System: Puede ver Activos'), ('sys_add_activo', 'System: Puede agregar Activos'), ('sys_change_activo', 'System: Puede cambiar Activos'), ('sys_delete_activo', 'System: Puede eliminar Activos')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre de la categoría', max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (opcional)')),
                ('codigo', models.CharField(help_text="Ingrese un código corto para la categoría (Ejemplo: 'EPP' para Equipos de Protección Personal)", max_length=20, unique=True, verbose_name='Código (opcional)')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'permissions': [('sys_view_categoria', 'System: Puede ver Categorías'), ('sys_add_categoria', 'System: Puede agregar Categorías'), ('sys_change_categoria', 'System: Puede cambiar Categorías'), ('sys_delete_categoria', 'System: Puede eliminar Categorías')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Compartimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ingrese el nombre del compartimento', max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (opcional)')),
                ('imagen', models.ImageField(blank=True, help_text='(Opcional) Imagen del compartimento', null=True, upload_to='compartimentos/imagen/main/', verbose_name='Imagen (opcional)')),
                ('imagen_thumb_medium', models.ImageField(blank=True, editable=False, null=True, upload_to='compartimentos/imagen/medium/', verbose_name='Thumbnail (600x600)')),
                ('imagen_thumb_small', models.ImageField(blank=True, editable=False, null=True, upload_to='compartimentos/imagen/small/', verbose_name='Thumbnail (50x50)')),
                ('codigo', models.CharField(editable=False, max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compartimento',
                'verbose_name_plural': 'Compartimentos',
                'ordering': ['ubicacion__nombre', 'nombre'],
                'permissions': [('sys_view_compartimento', 'System: Puede ver Compartimentos'), ('sys_add_compartimento', 'System: Puede agregar Compartimentos'), ('sys_change_compartimento', 'System: Puede cambiar Compartimentos'), ('sys_delete_compartimento', 'System: Puede eliminar Compartimentos')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre de la comuna', max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Comuna de Chile',
                'verbose_name_plural': 'Comunas de Chile',
                'permissions': [('sys_view_comuna', 'System: Puede ver Comunas de Chile'), ('sys_add_comuna', 'System: Puede agregar Comunas de Chile'), ('sys_change_comuna', 'System: Puede cambiar Comunas de Chile'), ('sys_delete_comuna', 'System: Puede eliminar Comunas de Chile')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ContactoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(help_text="Ej: 'Sucursal Iquique', 'Juan Pérez (Ventas)'", max_length=100, verbose_name='Nombre Sucursal/Contacto')),
                ('direccion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
            ],
            options={
                'verbose_name': 'Contacto de Proveedor',
                'verbose_name_plural': 'Contactos de Proveedor',
                'ordering': ['proveedor', 'nombre_contacto'],
                'permissions': [('sys_view_contactoproveedor', 'System: Puede ver Contactos de Proveedor'), ('sys_add_contactoproveedor', 'System: Puede agregar Contactos de Proveedor'), ('sys_change_contactoproveedor', 'System: Puede cambiar Contactos de Proveedor'), ('sys_delete_contactoproveedor', 'System: Puede eliminar Contactos de Proveedor')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entidad', models.CharField(max_length=255, verbose_name='Nombre Entidad (Ej: Clínica XYZ)')),
                ('rut_entidad', models.CharField(blank=True, max_length=12, null=True, verbose_name='RUT Entidad (Opcional)')),
                ('nombre_contacto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Contacto (Opcional)')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Contacto (Opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destinatario de Préstamo',
                'verbose_name_plural': 'Destinatarios de Préstamos',
                'ordering': ['nombre_entidad'],
                'permissions': [('sys_view_destinatario', 'System: Puede ver Destinatarios de Préstamos'), ('sys_add_destinatario', 'System: Puede agregar Destinatarios de Préstamos'), ('sys_change_destinatario', 'System: Puede cambiar Destinatarios de Préstamos'), ('sys_delete_destinatario', 'System: Puede eliminar Destinatarios de Préstamos')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre de la compañía', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (opcional)')),
                ('direccion', models.CharField(blank=True, help_text='Ingrese la dirección (calle y número) de la compañía', max_length=100, null=True, verbose_name='Dirección')),
                ('es_departamento', models.BooleanField(default=False, help_text='Seleccione si esta estación corresponde a un Cuerpo de Bomberos', verbose_name='Es Cuerpo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='estaciones/imagen/main/', verbose_name='Imagen de la compañía')),
                ('imagen_thumb_medium', models.ImageField(blank=True, editable=False, null=True, upload_to='estaciones/imagen/medium/', verbose_name='Thumbnail (600x600)')),
                ('imagen_thumb_small', models.ImageField(blank=True, editable=False, null=True, upload_to='estaciones/imagen/small/', verbose_name='Thumbnail (50x50)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='estaciones/logo/', verbose_name='Logo de la compañía')),
                ('logo_thumb_medium', models.ImageField(blank=True, editable=False, null=True, upload_to='estaciones/logo/medium/')),
                ('logo_thumb_small', models.ImageField(blank=True, editable=False, null=True, upload_to='estaciones/logo/small/')),
                ('codigo', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Código de Sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estación',
                'verbose_name_plural': 'Estaciones',
                'ordering': ['nombre'],
                'permissions': [('sys_view_estacion', 'System: Puede ver Estaciones'), ('sys_add_estacion', 'System: Puede agregar Estaciones'), ('sys_change_estacion', 'System: Puede cambiar Estaciones'), ('sys_delete_estacion', 'System: Puede eliminar Estaciones')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del estado', max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (opcional)')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'permissions': [('sys_view_estado', 'System: Puede ver Estados'), ('sys_add_estado', 'System: Puede agregar Estados'), ('sys_change_estado', 'System: Puede cambiar Estados'), ('sys_delete_estado', 'System: Puede eliminar Estados')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='LoteInsumo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_lote', models.CharField(blank=True, editable=False, help_text='ID Interno único generado por el sistema (Ej: E1-LOT-00001)', max_length=50, unique=True, verbose_name='Código de Lote (ID Interno)')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fecha_expiracion', models.DateField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('numero_lote_fabricante', models.CharField(blank=True, help_text='Número de lote del fabricante para trazabilidad.', max_length=100, null=True)),
                ('fecha_recepcion', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha de Recepción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lote de Insumo',
                'verbose_name_plural': 'Lotes de Insumos',
                'permissions': [('sys_view_loteinsumo', 'System: Puede ver Lotes de Insumos'), ('sys_add_loteinsumo', 'System: Puede agregar Lotes de Insumos'), ('sys_change_loteinsumo', 'System: Puede cambiar Lotes de Insumos'), ('sys_delete_loteinsumo', 'System: Puede eliminar Lotes de Insumos')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre de la marca', max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (opcional)')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'permissions': [('sys_view_marca', 'System: Puede ver Marcas'), ('sys_add_marca', 'System: Puede agregar Marcas'), ('sys_change_marca', 'System: Puede cambiar Marcas'), ('sys_delete_marca', 'System: Puede eliminar Marcas')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENT', 'Entrada'), ('SAL', 'Salida'), ('TRA', 'Transferencia'), ('AJU', 'Ajuste'), ('TRAS', 'Traslado'), ('PRE', 'Préstamo Externo'), ('DEV', 'Devolución de Préstamo')], max_length=4)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad_movida', models.IntegerField(help_text='Positivo para entradas/ajustes+, Negativo para salidas/ajustes-')),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_hora'],
                'permissions': [('sys_view_movimientoinventario', 'System: Puede ver Movimientos de Inventario'), ('sys_add_movimientoinventario', 'System: Puede agregar Movimientos de Inventario'), ('sys_change_movimientoinventario', 'System: Puede cambiar Movimientos de Inventario'), ('sys_delete_movimientoinventario', 'System: Puede eliminar Movimientos de Inventario')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Préstamo')),
                ('fecha_devolucion_esperada', models.DateField(blank=True, null=True, verbose_name='Fecha Devolución Esperada')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('PAR', 'Devuelto Parcialmente'), ('COM', 'Completado'), ('VEN', 'Vencido')], default='PEN', max_length=3)),
                ('notas_prestamo', models.TextField(blank=True, null=True, verbose_name='Notas/Motivo del Préstamo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
                'permissions': [('sys_view_prestamo', 'System: Puede ver Préstamos'), ('sys_add_prestamo', 'System: Puede agregar Préstamos'), ('sys_change_prestamo', 'System: Puede cambiar Préstamos'), ('sys_delete_prestamo', 'System: Puede eliminar Préstamos')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='PrestamoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_item', models.CharField(blank=True, max_length=255)),
                ('codigo_item', models.CharField(blank=True, max_length=50)),
                ('cantidad_prestada', models.PositiveIntegerField(default=1)),
                ('cantidad_devuelta', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Detalle de Préstamo',
                'verbose_name_plural': 'Detalles de Préstamos',
                'permissions': [('sys_view_prestamodetalle', 'System: Puede ver Detalles de Préstamos'), ('sys_add_prestamodetalle', 'System: Puede agregar Detalles de Préstamos'), ('sys_change_prestamodetalle', 'System: Puede cambiar Detalles de Préstamos'), ('sys_delete_prestamodetalle', 'System: Puede eliminar Detalles de Préstamos')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, help_text='SKU o código interno de la compañía para este producto.', max_length=50, null=True)),
                ('es_serializado', models.BooleanField(default=False, help_text='Marcar si este producto es un Activo que requiere seguimiento individual.')),
                ('costo_compra', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('vida_util_estacion_anos', models.PositiveIntegerField(blank=True, help_text='Regla de la estación. Si se deja en blanco, se usará la recomendación global.', null=True, verbose_name='Vida Útil (Años)')),
                ('es_expirable', models.BooleanField(default=0, verbose_name='¿Es expirable?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto de Compañía',
                'verbose_name_plural': 'Productos de Compañía',
                'permissions': [('sys_view_producto', 'System: Puede ver Productos de Compañía'), ('sys_add_producto', 'System: Puede agregar Productos de Compañía'), ('sys_change_producto', 'System: Puede cambiar Productos de Compañía'), ('sys_delete_producto', 'System: Puede eliminar Productos de Compañía')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ProductoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oficial', models.CharField(help_text="Nombre estandarizado del producto. Ej: 'Equipo de Respiración Autónoma SCBA'", max_length=255)),
                ('descripcion_general', models.TextField(blank=True, help_text='Descripción general del producto, sus usos y características.', null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('gtin', models.CharField(blank=True, help_text='GTIN/EAN/UPC del fabricante, si aplica.', max_length=50, null=True, unique=True)),
                ('vida_util_recomendada_anos', models.PositiveIntegerField(blank=True, help_text='Vida útil en años según el fabricante (para equipos).', null=True, verbose_name='Vida útil recomendada (años)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos_globales/imagen/main/', verbose_name='Imagen (opcional)')),
                ('imagen_thumb_medium', models.ImageField(blank=True, editable=False, null=True, upload_to='productos_globales/imagen/medium/', verbose_name='Thumbnail (600x600)')),
                ('imagen_thumb_small', models.ImageField(blank=True, editable=False, null=True, upload_to='productos_globales/imagen/small/', verbose_name='Thumbnail (50x50)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto Global',
                'verbose_name_plural': 'Productos Globales',
                'permissions': [('sys_view_productoglobal', 'System: Puede ver Productos Globales'), ('sys_add_productoglobal', 'System: Puede agregar Productos Globales'), ('sys_change_productoglobal', 'System: Puede cambiar Productos Globales'), ('sys_delete_productoglobal', 'System: Puede eliminar Productos Globales')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del proveedor', max_length=50, verbose_name='Nombre')),
                ('rut', models.CharField(help_text='Ingrese el rut de la compañía', max_length=10, verbose_name='Rol Único Tributario (RUT)')),
                ('giro_comercial', models.CharField(blank=True, help_text='(Opcional) Ingrese el giro comercial del proveedor', max_length=100, null=True, verbose_name='Giro')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
                'permissions': [('sys_view_proveedor', 'System: Puede ver Proveedores'), ('sys_add_proveedor', 'System: Puede agregar Proveedores'), ('sys_change_proveedor', 'System: Puede cambiar Proveedores'), ('sys_delete_proveedor', 'System: Puede eliminar Proveedores')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre de la región', max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Región de Chile',
                'verbose_name_plural': 'Regiones de Chile',
                'permissions': [('sys_view_region', 'System: Puede ver Regiones de Chile'), ('sys_add_region', 'System: Puede agregar Regiones de Chile'), ('sys_change_region', 'System: Puede cambiar Regiones de Chile'), ('sys_delete_region', 'System: Puede eliminar Regiones de Chile')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='RegistroUsoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_uso', models.DateTimeField(verbose_name='Fecha y Hora de Uso')),
                ('horas_registradas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Horas Registradas')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas/Observaciones')),
                ('fecha_creacion_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación del Registro')),
            ],
            options={
                'verbose_name': 'Registro de Uso de Activo',
                'verbose_name_plural': 'Registros de Uso de Activos',
                'ordering': ['-fecha_uso'],
                'permissions': [('sys_view_registrousoactivo', 'System: Puede ver Registros de Uso de Activos'), ('sys_add_registrousoactivo', 'System: Puede agregar Registros de Uso de Activos'), ('sys_change_registrousoactivo', 'System: Puede cambiar Registros de Uso de Activos'), ('sys_delete_registrousoactivo', 'System: Puede eliminar Registros de Uso de Activos')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='TipoEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del tipo de estado', max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (opcional)')),
            ],
            options={
                'verbose_name': 'Tipo de estado',
                'verbose_name_plural': 'Tipos de estado',
                'permissions': [('sys_view_tipoestado', 'System: Puede ver Tipos de estado'), ('sys_add_tipoestado', 'System: Puede agregar Tipos de estado'), ('sys_change_tipoestado', 'System: Puede cambiar Tipos de estado'), ('sys_delete_tipoestado', 'System: Puede eliminar Tipos de estado')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='TipoUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del tipo de ubicación', max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (opcional)')),
            ],
            options={
                'verbose_name': 'Tipo de ubicación',
                'verbose_name_plural': 'Tipos de ubicación',
                'permissions': [('sys_view_tipoubicacion', 'System: Puede ver Tipos de ubicación'), ('sys_add_tipoubicacion', 'System: Puede agregar Tipos de ubicación'), ('sys_change_tipoubicacion', 'System: Puede cambiar Tipos de ubicación'), ('sys_delete_tipoubicacion', 'System: Puede eliminar Tipos de ubicación')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del tipo de vehículo', max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (opcional)')),
            ],
            options={
                'verbose_name': 'Tipo de vehículo',
                'verbose_name_plural': 'Tipos de vehículos',
                'permissions': [('sys_view_tipovehiculo', 'System: Puede ver Tipos de vehículos'), ('sys_add_tipovehiculo', 'System: Puede agregar Tipos de vehículos'), ('sys_change_tipovehiculo', 'System: Puede cambiar Tipos de vehículos'), ('sys_delete_tipovehiculo', 'System: Puede eliminar Tipos de vehículos')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ingrese el nombre de la ubicación', max_length=128, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='(Opcional) Ingrese una descripción de la ubicación', null=True, verbose_name='Descripción (opcional)')),
                ('direccion', models.CharField(blank=True, help_text='(opcional) Ingrese la dirección en el caso de que la ubicación se encuentre en una dirección distinta a la de la estación (Ejemplo: AV GIRASOL #1234)', max_length=128, null=True, verbose_name='Dirección (opcional)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ubicaciones/imagen/main/', verbose_name='Imagen (opcional)')),
                ('imagen_thumb_medium', models.ImageField(blank=True, editable=False, null=True, upload_to='ubicaciones/imagen/medium/', verbose_name='Thumbnail (600x600)')),
                ('imagen_thumb_small', models.ImageField(blank=True, editable=False, null=True, upload_to='ubicaciones/imagen/small/', verbose_name='Thumbnail (50x50)')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'permissions': [('sys_view_ubicacion', 'System: Puede ver Ubicaciones'), ('sys_add_ubicacion', 'System: Puede agregar Ubicaciones'), ('sys_change_ubicacion', 'System: Puede cambiar Ubicaciones'), ('sys_delete_ubicacion', 'System: Puede eliminar Ubicaciones')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(blank=True, help_text='(Opcional) Ingrese la patente del vehículo', max_length=10, null=True, unique=True, verbose_name='Patente (Opcional)')),
                ('modelo', models.CharField(blank=True, help_text='(Opcional) Ingrese el modelo del vehículo', max_length=100, null=True, verbose_name='Modelo (Opcional)')),
                ('chasis', models.CharField(blank=True, help_text='(Opcional) Ingrese el número de chasis', max_length=100, null=True, unique=True, verbose_name='Chasis (Opcional)')),
                ('anho', models.CharField(blank=True, help_text='(Opcional) Ingrese el año del vehículo', max_length=4, null=True, verbose_name='Año (Opcional)')),
            ],
            options={
                'permissions': [('sys_view_vehiculo', 'System: Puede ver Vehículos'), ('sys_add_vehiculo', 'System: Puede agregar Vehículos'), ('sys_change_vehiculo', 'System: Puede cambiar Vehículos'), ('sys_delete_vehiculo', 'System: Puede eliminar Vehículos')],
                'default_permissions': [],
            },
        ),
    ]
