# Generated by Django 5.2.1 on 2025-11-22 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activo',
            name='compartimento',
            field=models.ForeignKey(help_text='Seleccionar compartimento donde se encuentra la existencia', on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.compartimento', verbose_name='Compartimento'),
        ),
        migrations.AddField(
            model_name='contactoproveedor',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.comuna', verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinatarios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estacion',
            name='comuna',
            field=models.ForeignKey(help_text='Seleccione la comuna correspondiente', on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.comuna', verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='gestion_inventario.estacion'),
        ),
        migrations.AddField(
            model_name='contactoproveedor',
            name='estacion_especifica',
            field=models.ForeignKey(blank=True, help_text='Si este contacto es solo relevante para una estación en particular.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_inventario.estacion', verbose_name='Específico para Estación'),
        ),
        migrations.AddField(
            model_name='activo',
            name='estacion',
            field=models.ForeignKey(help_text='Seleccionar estación propietaria de la existencia', on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.estacion', verbose_name='Estación'),
        ),
        migrations.AddField(
            model_name='activo',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.estado', verbose_name='Estado de la existencia/lote'),
        ),
        migrations.AddField(
            model_name='loteinsumo',
            name='compartimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.compartimento', verbose_name='Compartimento'),
        ),
        migrations.AddField(
            model_name='loteinsumo',
            name='estado',
            field=models.ForeignKey(help_text='Estado actual del lote (Disponible, Anulado, etc.)', on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.estado', verbose_name='Estado del Lote'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion_inventario.activo'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='compartimento_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_entrada', to='gestion_inventario.compartimento'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='compartimento_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_salida', to='gestion_inventario.compartimento'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.estacion'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='lote_insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion_inventario.loteinsumo'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_recibidos', to='gestion_inventario.destinatario'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_realizados', to='gestion_inventario.estacion'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='usuario_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_gestionados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prestamodetalle',
            name='activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='gestion_inventario.activo'),
        ),
        migrations.AddField(
            model_name='prestamodetalle',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='gestion_inventario.loteinsumo'),
        ),
        migrations.AddField(
            model_name='prestamodetalle',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_prestados', to='gestion_inventario.prestamo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.estacion', verbose_name='Estación Origen'),
        ),
        migrations.AddField(
            model_name='loteinsumo',
            name='producto',
            field=models.ForeignKey(limit_choices_to={'es_serializado': False}, on_delete=django.db.models.deletion.CASCADE, to='gestion_inventario.producto'),
        ),
        migrations.AddField(
            model_name='activo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='productoglobal',
            name='categoria',
            field=models.ForeignKey(help_text='Seleccione la categoría a la que corresponde el producto', on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.categoria'),
        ),
        migrations.AddField(
            model_name='productoglobal',
            name='marca',
            field=models.ForeignKey(blank=True, help_text='Seleccione la marca del producto', null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_global',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variantes_locales', to='gestion_inventario.productoglobal'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_principal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gestion_inventario.contactoproveedor', verbose_name='Contacto Principal'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estacion_creadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.estacion', verbose_name='Estación Origen'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_preferido',
            field=models.ForeignKey(blank=True, help_text='Seleccione el proveedor preferido para este producto', null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.proveedor', verbose_name='Proveedor preferido'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='proveedor_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to='gestion_inventario.proveedor'),
        ),
        migrations.AddField(
            model_name='contactoproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='gestion_inventario.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='activo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(help_text='Seleccione la región correspondiente', on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.region', verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='registrousoactivo',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_uso', to='gestion_inventario.activo', verbose_name='Activo Utilizado'),
        ),
        migrations.AddField(
            model_name='registrousoactivo',
            name='usuario_registra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra'),
        ),
        migrations.AddField(
            model_name='estado',
            name='tipo_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.tipoestado', verbose_name='Tipo de estado'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='estacion',
            field=models.ForeignKey(help_text='Seleccionar estación correspondiente', on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.estacion', verbose_name='Estación'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='tipo_ubicacion',
            field=models.ForeignKey(help_text='Seleccione el tipo de ubicación', on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.tipoubicacion', verbose_name='Tipo de sección'),
        ),
        migrations.AddField(
            model_name='compartimento',
            name='ubicacion',
            field=models.ForeignKey(help_text='Seleccionar ubicación correspondiente', on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.ubicacion', verbose_name='Ubicación/sección'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='marca',
            field=models.ForeignKey(blank=True, help_text='(Opcional) Ingrese la marca del vehículo', null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.marca', verbose_name='Marca (Opcional)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.ForeignKey(help_text='Ingrese el tipo de vehículo', on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.tipovehiculo', verbose_name='Tipo de vehículo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ubicacion',
            field=models.OneToOneField(limit_choices_to={'tipo_ubicacion__nombre': 'Vehículo'}, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_vehiculo', to='gestion_inventario.ubicacion'),
        ),
        migrations.AlterUniqueTogether(
            name='destinatario',
            unique_together={('estacion', 'nombre_entidad')},
        ),
        migrations.AddConstraint(
            model_name='productoglobal',
            constraint=models.UniqueConstraint(fields=('marca', 'modelo'), name='unique_marca_modelo_cuando_no_nulos'),
        ),
        migrations.AddConstraint(
            model_name='productoglobal',
            constraint=models.UniqueConstraint(condition=models.Q(('marca__isnull', True)), fields=('nombre_oficial',), name='unique_nombre_oficial_para_genericos'),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('estacion', 'producto_global'), ('estacion', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='activo',
            unique_together={('estacion', 'codigo_activo')},
        ),
    ]
