# Generated by Django 5.2.1 on 2025-12-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0005_prestamodetalle_fecha_ultima_devolucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinatario',
            name='creado_por',
        ),
    ]
