# Generated by Django 5.2.1 on 2025-11-22 22:34

import apps.gestion_documental.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Un título claro para el documento.', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Breve descripción del contenido del documento.', null=True)),
                ('fecha_documento', models.DateField(help_text='Fecha en que se emitió o creó el documento original.')),
                ('archivo', models.FileField(help_text='Archivo digitalizado (PDF, JPG, PNG).', max_length=255, upload_to=apps.gestion_documental.models.ruta_archivo_historico)),
                ('preview_imagen', models.ImageField(blank=True, editable=False, help_text='Imagen generada automáticamente de la primera página.', null=True, upload_to='documentos/previews/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento Histórico',
                'verbose_name_plural': 'Documentos Históricos',
                'ordering': ['-fecha_documento'],
                'permissions': [('sys_view_documentohistorico', 'System: Puede ver Documentos Históricos'), ('sys_add_documentohistorico', 'System: Puede agregar Documentos Históricos'), ('sys_change_documentohistorico', 'System: Puede cambiar Documentos Históricos'), ('sys_delete_documentohistorico', 'System: Puede eliminar Documentos Históricos')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento Histórico',
                'verbose_name_plural': 'Tipos de Documentos Históricos',
                'ordering': ['nombre'],
                'permissions': [('sys_view_tipodocumento', 'System: Puede ver Tipos de Documentos Históricos'), ('sys_add_tipodocumento', 'System: Puede agregar Tipos de Documentos Históricos'), ('sys_change_tipodocumento', 'System: Puede cambiar Tipos de Documentos Históricos'), ('sys_delete_tipodocumento', 'System: Puede eliminar Tipos de Documentos Históricos')],
                'default_permissions': [],
            },
        ),
    ]
