# Generated by Django 5.2.1 on 2025-11-22 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_documental', '0001_initial'),
        ('gestion_inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentohistorico',
            name='estacion',
            field=models.ForeignKey(help_text='Estación a la que pertenece este documento.', on_delete=django.db.models.deletion.PROTECT, to='gestion_inventario.estacion'),
        ),
    ]
