# Generated by Django 5.2.1 on 2025-11-22 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_documental', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentohistorico',
            name='usuario_registra',
            field=models.ForeignKey(blank=True, help_text='Usuario que subió el documento al sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentohistorico',
            name='tipo_documento',
            field=models.ForeignKey(help_text='Clasificación del documento (ej. Libro de Actas).', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='gestion_documental.tipodocumento'),
        ),
    ]
