# Generated by Django 5.2.1 on 2025-12-15 17:07

import apps.gestion_documental.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documental', '0004_documentohistorico_es_confidencial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentohistorico',
            name='archivo',
            field=models.FileField(help_text='Archivo digitalizado (PDF, JPG, PNG).', max_length=255, upload_to=apps.gestion_documental.models.ruta_archivo_historico, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
