# Generated by Django 5.2.1 on 2025-11-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Alergia',
                'verbose_name_plural': 'Alergias',
                'ordering': ['nombre'],
                'permissions': [('sys_view_alergia', 'System: Puede ver Alergias'), ('sys_add_alergia', 'System: Puede agregar Alergias'), ('sys_change_alergia', 'System: Puede cambiar Alergias'), ('sys_delete_alergia', 'System: Puede eliminar Alergias')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Cirugía',
                'verbose_name_plural': 'Cirugías',
                'ordering': ['nombre'],
                'permissions': [('sys_view_cirugia', 'System: Puede ver Cirugías'), ('sys_add_cirugia', 'System: Puede agregar Cirugías'), ('sys_change_cirugia', 'System: Puede cambiar Cirugías'), ('sys_delete_cirugia', 'System: Puede eliminar Cirugías')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Contacto de Emergencia',
                'verbose_name_plural': 'Contactos de Emergencia',
                'permissions': [('sys_view_contactoemergencia', 'System: Puede ver Contactos de Emergencia'), ('sys_add_contactoemergencia', 'System: Puede agregar Contactos de Emergencia'), ('sys_change_contactoemergencia', 'System: Puede cambiar Contactos de Emergencia'), ('sys_delete_contactoemergencia', 'System: Puede eliminar Contactos de Emergencia')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Enfermedad',
                'verbose_name_plural': 'Enfermedades',
                'ordering': ['nombre'],
                'permissions': [('sys_view_enfermedad', 'System: Puede ver Enfermedades'), ('sys_add_enfermedad', 'System: Puede agregar Enfermedades'), ('sys_change_enfermedad', 'System: Puede cambiar Enfermedades'), ('sys_delete_enfermedad', 'System: Puede eliminar Enfermedades')],
                'default_permissions': [],
            },
        ),
    ]
