# Generated by Django 5.2.1 on 2025-11-22 22:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_medica', '0001_initial'),
        ('gestion_voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('voluntario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ficha_medica', serialize=False, to='gestion_voluntarios.voluntario')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Usar punto (.) para decimal', max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('altura_mts', models.DecimalField(blank=True, decimal_places=2, help_text='Ej: 1.75', max_digits=3, null=True, verbose_name='Altura (mts)')),
                ('presion_arterial_sistolica', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Presión arterial Sistólica')),
                ('presion_arterial_diastolica', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Presión arterial Diastólica')),
                ('observaciones_generales', models.TextField(blank=True, help_text='Anotaciones relevantes no cubiertas en otros campos.', null=True, verbose_name='Observaciones Generales')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ficha Médica',
                'verbose_name_plural': 'Fichas Médicas',
                'permissions': [('sys_view_fichamedica', 'System: Puede ver Fichas Médicas'), ('sys_add_fichamedica', 'System: Puede agregar Fichas Médicas'), ('sys_change_fichamedica', 'System: Puede cambiar Fichas Médicas'), ('sys_delete_fichamedica', 'System: Puede eliminar Fichas Médicas')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='GrupoSanguineo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Grupo sanguíneo',
                'verbose_name_plural': 'Grupos sanguíneos',
                'ordering': ['nombre'],
                'permissions': [('sys_view_gruposanguineo', 'System: Puede ver Grupos sanguíneos'), ('sys_add_gruposanguineo', 'System: Puede agregar Grupos sanguíneos'), ('sys_change_gruposanguineo', 'System: Puede cambiar Grupos sanguíneos'), ('sys_delete_gruposanguineo', 'System: Puede eliminar Grupos sanguíneos')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nombre'],
                'permissions': [('sys_view_medicamento', 'System: Puede ver Medicamentos'), ('sys_add_medicamento', 'System: Puede agregar Medicamentos'), ('sys_change_medicamento', 'System: Puede cambiar Medicamentos'), ('sys_delete_medicamento', 'System: Puede eliminar Medicamentos')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='SistemaSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Sistema de salud',
                'verbose_name_plural': 'Sistemas de salud',
                'ordering': ['nombre'],
                'permissions': [('sys_view_sistemasalud', 'System: Puede ver Sistemas de salud'), ('sys_add_sistemasalud', 'System: Puede agregar Sistemas de salud'), ('sys_change_sistemasalud', 'System: Puede cambiar Sistemas de salud'), ('sys_delete_sistemasalud', 'System: Puede eliminar Sistemas de salud')],
                'default_permissions': [],
            },
        ),
        migrations.AddField(
            model_name='contactoemergencia',
            name='voluntario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to='gestion_voluntarios.voluntario'),
        ),
        migrations.CreateModel(
            name='FichaMedicaCirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cirugia', models.DateField(blank=True, null=True, verbose_name='Fecha (aprox.)')),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('cirugia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_medica.cirugia')),
                ('ficha_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirugias', to='gestion_medica.fichamedica')),
            ],
            options={
                'verbose_name': 'Cirugía de Ficha',
                'verbose_name_plural': 'Cirugías de Ficha',
                'ordering': ['-fecha_cirugia'],
                'permissions': [('sys_view_fichamedicacirugia', 'System: Puede ver Cirugías de Ficha'), ('sys_add_fichamedicacirugia', 'System: Puede agregar Cirugías de Ficha'), ('sys_change_fichamedicacirugia', 'System: Puede cambiar Cirugías de Ficha'), ('sys_delete_fichamedicacirugia', 'System: Puede eliminar Cirugías de Ficha')],
                'default_permissions': [],
            },
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='grupo_sanguineo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_medica.gruposanguineo', verbose_name='Grupo Sanguíneo'),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='sistema_salud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_medica.sistemasalud', verbose_name='Sistema de Salud'),
        ),
        migrations.CreateModel(
            name='FichaMedicaAlergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(blank=True, help_text="Ej: 'Reacción grave', 'Solo produce picazón'", max_length=255, null=True)),
                ('alergia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_medica.alergia')),
                ('ficha_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alergias', to='gestion_medica.fichamedica')),
            ],
            options={
                'verbose_name': 'Alergia de Ficha',
                'verbose_name_plural': 'Alergias de Ficha',
                'permissions': [('sys_view_fichamedicaalergia', 'System: Puede ver Alergias de Ficha'), ('sys_add_fichamedicaalergia', 'System: Puede agregar Alergias de Ficha'), ('sys_change_fichamedicaalergia', 'System: Puede cambiar Alergias de Ficha'), ('sys_delete_fichamedicaalergia', 'System: Puede eliminar Alergias de Ficha')],
                'default_permissions': [],
                'unique_together': {('ficha_medica', 'alergia')},
            },
        ),
        migrations.CreateModel(
            name='FichaMedicaEnfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(blank=True, help_text="Ej: 'Crónica', 'En tratamiento'", max_length=255, null=True)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_medica.enfermedad')),
                ('ficha_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermedades', to='gestion_medica.fichamedica')),
            ],
            options={
                'verbose_name': 'Enfermedad de Ficha',
                'verbose_name_plural': 'Enfermedades de Ficha',
                'permissions': [('sys_view_fichamedicaenfermedad', 'System: Puede ver Enfermedades de Ficha'), ('sys_add_fichamedicaenfermedad', 'System: Puede agregar Enfermedades de Ficha'), ('sys_change_fichamedicaenfermedad', 'System: Puede cambiar Enfermedades de Ficha'), ('sys_delete_fichamedicaenfermedad', 'System: Puede eliminar Enfermedades de Ficha')],
                'default_permissions': [],
                'unique_together': {('ficha_medica', 'enfermedad')},
            },
        ),
        migrations.CreateModel(
            name='FichaMedicaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis_frecuencia', models.CharField(blank=True, help_text="Ej: '10mg cada 8 horas'", max_length=100, null=True, verbose_name='Dosificación')),
                ('ficha_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='gestion_medica.fichamedica')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_medica.medicamento')),
            ],
            options={
                'verbose_name': 'Medicamento de Ficha',
                'verbose_name_plural': 'Medicamentos de Ficha',
                'permissions': [('sys_view_fichamedicamedicamento', 'System: Puede ver Medicamentos de Ficha'), ('sys_add_fichamedicamedicamento', 'System: Puede agregar Medicamentos de Ficha'), ('sys_change_fichamedicamedicamento', 'System: Puede cambiar Medicamentos de Ficha'), ('sys_delete_fichamedicamedicamento', 'System: Puede eliminar Medicamentos de Ficha')],
                'default_permissions': [],
                'unique_together': {('ficha_medica', 'medicamento')},
            },
        ),
    ]
